### ISSUE TITLE
How to recompile the minified files?

### ISSUE THREAD

**Issue by katlimruiz** [creativetimofficial/soft-ui-dashboard-laravel#4]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository (for multi-repository projects)
>>> Well, this is the package I'm using, so it would be expected to contain this issue I suppose.

# Expected Behavior

Once I modify the file `public\assets\js\soft-ui-dashboard.js`, I need to minify it so it converts to `public\assets\js\soft-ui-dashboard.min.js`.

**It is ok if I need to do it manually.**

# Current Behavior

I ran `npm run dev`, which didn't generate it.

# Failure Information (for bugs)

No bugs. I need instructions on recompiling the javascript files in a repeatable and consistent (to your implementation) way.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Windows
* Operating System: Windows 11
* Browser and Version: Chrome

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative TIM products!

We have updated the repo, if you want to recompile the file soft-ui-dashboard.min.js you need to call npm run prod. 

Let me know if that helps.
